FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

ARG AZURE_DEVOPS_PAT

COPY . .

RUN test -n "$AZURE_DEVOPS_PAT"

RUN dotnet nuget remove source DhaniProjetos || true

RUN dotnet nuget add source "https://pkgs.dev.azure.com/DhaniProjetos/_packaging/DhaniProjetos/nuget/v3/index.json" \
    --name "DhaniProjetos" \
    --username "az" \
    --password "$AZURE_DEVOPS_PAT" \
    --store-password-in-clear-text

RUN dotnet restore src/MinhaCarteira.sln
RUN dotnet publish src/MinhaCarteira.AppCliente -c Release -o /app/publish/client --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish/client .

ENV ASPNETCORE_URLS=http://+:${PORT}

ENTRYPOINT ["dotnet", "MinhaCarteira.AppCliente.dll"]